jenkins:
  url: 'http://jenkins.domain.com'
  version_artifact: 'version.yaml.txt'
#  version_artifacts:
#    'build.properties': 'txt'
#    'version.yaml': 'yaml'

testrail:
  url: 'http://mirantis.testrail.com'
  username: 'user@example.com'
  password: 'password'
  project: 'Contrail plugin'
  test_suite: 'Contrail Plugin v2.x.x'
  milestone: '7.0'
  test_suite: '${testrail.milestone} Swarm'
  test_section: 'All'
  test_include: null
  test_exclude: null
  previous_results_depth: 5
  suite_configurations:
    'Contrail distributor':
      - 'Juniper contrail'
  operating_systems:
    centos: 'Centos 6.5'
    ubuntu: 'Ubuntu 14.04'
launchpad:
    project: 'fuel'
    milestone: '8.0'
    release_statuses:
      released: 'Fix Released'
      invalid: 'Invalid'

test_result:
#  tmpl_test_plan_name: '%(artifacts.build.TEST_GROUP)s--%(artifacts.build.BUILD_ID)s--%(artifacts.nightly.BUILD_DISPLAY_NAME)s'
  tmpl_test_plan_name: 'Contrail Plugin v3.0.0 ISO#7.0-301 RPM#31'
#  tmpl_milestone: '%(artifacts.build.milestone)s'
  tmpl_milestone: 'Fuel Contrail Plugin v3.0.0'
  tmpl_iso_number: '7.0-301'
  info_sources:
    artifacts:
      'build.properties': 'build'
      'nightly.properties': 'nightly'



other:
  log_level: DEBUG
  log_dir: /var/log/jenkins2testrail.log
  expand_groups:
    - setup_master
    - prepare_release
    - prepare_slaves_1
    - prepare_slaves_3
    - prepare_slaves_5
    - prepare_slaves_9

